### ISSUE TITLE
Browser warning about SEC-Error-Expired-Certificate

### ISSUE THREAD

**Issue by ghost** [edemaine/font-tetris#2]
The Website has a expired Certificate.

Here is the whole Error Code:

https://erikdemaine.org/fonts/tetris/

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

-----BEGIN CERTIFICATE-----
MIIFJjCCBA6gAwIBAgISA0vGfd9s4XZI38JApAxZn5FcMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzA2MDExNzM5MzRaFw0yMzA4MzAxNzM5MzNaMBoxGDAWBgNVBAMT
D2VyaWtkZW1haW5lLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
ANnLbocTckAToCVWGTk7nf/iBBxC1o9+HWHZB18kfBdeCRXzD5I9CnTnN1dE8skk
D1NfdaBTJUkJ/fK/MR9nnPcahw4PWDU5exB2FPbZe7Bb3A6sf0wn5qJYTFe3I54w
YtiiaXmnmF7B7C5P4mIG4/dgGUwAmzZheaaHbmSGqFZkIBKAvNwQFmcNcmkhYbhE
YIt6Iq6/BiuzNz0yy7KLw27GxPU4DINprnJ/oLw7P0A7LZJG49asLonEEYN+X1UV
ejjkRRj7vbSPg2u3QSo4flw1R4QMzkRxf2d0cr7v+UkowjTSnYe/uvB70NOpnAG9
zk8Gf3DylG4nLG5I8w1PefUCAwEAAaOCAkwwggJIMA4GA1UdDwEB/wQEAwIFoDAd
BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNV
HQ4EFgQUxuUHoNZVB4GIh7bx3SLZXEipmGcwHwYDVR0jBBgwFoAUFC6zF7dYVsuu
UAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8v
cjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9y
Zy8wGgYDVR0RBBMwEYIPZXJpa2RlbWFpbmUub3JnMEwGA1UdIARFMEMwCAYGZ4EM
AQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0
c2VuY3J5cHQub3JnMIIBBgYKKwYBBAHWeQIEAgSB9wSB9ADyAHcAejKMVNi3LbYg
6jjgUh7phBZwMhOFTTvSK8E6V6NS61IAAAGIeEIMfQAABAMASDBGAiEAk/TXNyNF
DxVoK+Ra/N+pic1NRiGK2q6V9Ngg2ks1yDMCIQCL7AbPAd0YNbYukVc4eEOixDdt
7XyqT3PV3kYkFE0tjgB3AOg+0No+9QY1MudXKLyJa8kD08vREWvs62nhd31tBr1u
AAABiHhCDIQAAAQDAEgwRgIhAIhFkCHbpWuidPB6SnIRyS/o+P00LES/3fZov+Ji
2MOuAiEA/4ov5OWpu5MnQOzcpN6N466/cv4c7lBlWJ9BrCiPMu8wDQYJKoZIhvcN
AQELBQADggEBABUd3V98l2Wf6OVtbPU/0mACcj0ttJYsNSH2gLanDVPEnIiPIKzv
xrc+UF+OcZs6Vv6VRDbOSG4m/oIRQmbu4sndXwP+2MfR9QvdZ3+4S7Cp6GBIMEp0
wuoaz6Nuo9dv24f8vojO6l/sLVaPRVfRST97fYXLDFEka+zUGgd7p/ww192KJFjd
aToyaxNIZKD5KCzIXizTeBzZC+M2EGehGLq/sOWhA5g5Wy1BwQ0NIbZIRdOmfdI2
4PiGzHdODBhn3GUVGM9ZjO86dDeDzl0ZANifWgvqefJE8XX53GP3uiCfAdrhnDFB
q5T4Mx1hAH6Nt6y3/gxhyx7D57z0A8fDvDs=
-----END CERTIFICATE-----

**Comment by ghost** [comment]
Problem solved. Thanks

**Comment by edemaine** [comment]
Thanks for the report! You were the first. 🙂
